---
version: "3.6"
services:
  es_server:
    image: es_server
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      MYSQL_HOST: es_database
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_DATABASE: engelsystem
    ports:
      - "127.0.0.1:5000:80"
    env_file: deployment.env
    networks:
      - database
      - internet
    depends_on:
      - es_database
    volumes:
      - /opt/engelsystem/engelsystem/config:/var/www/config:ro
    restart: unless-stopped
  es_database:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: engelsystem
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      - database
    restart: unless-stopped
volumes:
  db: {}

networks:
  database:
    internal: true
  internet:
